'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Hangman.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arm_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arm_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arm_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arm_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property body() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("body", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property head() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("head", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property leg_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leg_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property leg_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leg_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A
        '''a
        '''aback
        '''abacus
        '''abandon
        '''abandoned
        '''abandonment
        '''abashed
        '''abate
        '''abbey
        '''abbr.
        '''abbreviate
        '''abbreviation
        '''ABC
        '''ABC&apos;s
        '''abdicate
        '''abdication
        '''abdomen
        '''abdominal
        '''abduct
        '''abduction
        '''aberration
        '''abet
        '''abhor
        '''abhorrence
        '''abhorrent
        '''abide
        '''abiding
        '''ability
        '''abject
        '''ablaze
        '''able
        '''able-bodied
        '''ably
        '''abnormal
        '''abnormality
        '''abnormally
        '''aboard
        '''abolish
        '''abolition
        '''abolitionist
        '''abominable
        '''aboriginal
        '''aborigine
        '''abort
        '''abortion
        '''abortive
        '''abound
        '''about
        '''about-face
        '''above
        '''aboveboard
        '''abrasive
        '''abrasively
        '''abreast        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Wordlist() As String
            Get
                Return ResourceManager.GetString("Wordlist", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
